/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3D/laptop.glb --types 
*/

import * as THREE from 'three'
import React, {useRef, useLayoutEffect, JSX} from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'
import gsap from 'gsap'
import {ScrollTrigger} from 'gsap/ScrollTrigger'

// Register GSAP Plugin
gsap.registerPlugin(ScrollTrigger);

type GLTFResult = GLTF & {
    nodes: {
        Frame_ComputerFrame_0: THREE.Mesh
        Screen_ComputerScreen_0: THREE.Mesh
    }
    materials: {
        ['ComputerFrame.001']: THREE.MeshStandardMaterial
        ['ComputerScreen.001']: THREE.MeshStandardMaterial
    }
    animations: GLTFAction[]
}

export function LaptopModel(props: JSX.IntrinsicElements['group']) {
    const {nodes, materials} = useGLTF('/3D/laptop.glb') as GLTFResult

    // Refs to control animations
    const laptopRef = useRef<THREE.Group>(null)
    const lidRef = useRef<THREE.Group>(null)

    useLayoutEffect(() => {
        if (!lidRef.current || !laptopRef.current) return;

        // 2. Set Initial State: Closed
        // Note: Adjust 'x' slightly if it clips through the keyboard
        // 3. Define the Animation
        const tl = gsap.timeline({
            scrollTrigger: {
                trigger: "#hero", // Make sure this ID matches your page container
                start: "top top",           // Start opening when section hits 60% of viewport
                end: "bottom 50% screen",          // Fully open when bottom hits 40%
                scrub: 1,                   // Smooth scrubbing
                markers: false
            }
        });

        tl.fromTo(laptopRef.current.position, {
                x: 0,
                y: -1,
                z: 0
            },
            {
                x: 0,
                y: -9,
                z: 0,
                duration: 1,
                ease: "power2.out"
            })

        tl.fromTo(laptopRef.current.scale,
            {
                x: 0.15,
                y: 0.15,
                z: 0.15
            },
            {
                x: .7,
                y: .7,
                z: .7,
                duration: 1,
                ease: "power2.out"
            },
            "<"
        );

        tl.fromTo(lidRef.current.rotation,
            {x: Math.PI + 1.55},
            {
                x: Math.PI,
                duration: 1,
                ease: "power2.out"
            }, "<"
        )

        tl.fromTo("#laptop-container", {
                opacity: 1,
            },
            {
                opacity: 0,
                duration: 1,
                ease: "power2.out"
        });

    }, []);

    return (
        <group {...props} dispose={null}>
            <group ref={laptopRef}>

                {/* --- BOTTOM CHASSIS (Static) --- */}
                <mesh
                    geometry={nodes.Frame_ComputerFrame_0.geometry}
                    material={materials['ComputerFrame.001']}
                    position={[0, 0.976, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                />

                {/* --- LID / SCREEN GROUP (Animated) --- */}
                {/* We moved the Position/Rotation from the mesh to this group to create a Hinge */}
                <group
                    ref={lidRef}
                    position={[0, 0.65, -10.3]}
                    rotation={[Math.PI, 0, Math.PI]}
                >
                    <mesh
                        geometry={nodes.Screen_ComputerScreen_0.geometry}
                        material={materials['ComputerScreen.001']}
                        // Position and Rotation are removed (0,0,0) so it sits at the pivot point
                        // We keep Scale on the mesh to avoid distorting the rotation axis
                        scale={[100, 100, 88.235]}
                    />
                </group>

            </group>
        </group>
    )
}

useGLTF.preload('/3D/laptop.glb')